# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

conda:
  environment: requirements/rtd-conda-environment.yml

# Comment out for now while debugging conda build.
# python:
#   version: 3.7
#   install:
#     - requirements: requirements/rtd.txt
#     # Install using setuptools so that we don't automatically pull in msprime
#     # (which won't build because GSL is missing).
#     - method: setuptools 
#       path: .
